amcl:
  ros__parameters:
    use_sim_time: true
    scan_topic: scan
    base_frame_id: base_footprint
    odom_frame_id: odom
    global_frame_id: map

map_server:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.0
      max_vel_x: 0.26
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.5
      critics: ["ObstacleFootprintCritic", "GoalAlignCritic", "PathAlignCritic", "PathDistCritic", "GoalDistCritic"]

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

behavior_server:
  ros__parameters:
    use_sim_time: true

velocity_smoother:
  ros__parameters:
    use_sim_time: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: base_link
    footprint: "[[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]"
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer", "static_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

global_costmap:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: base_link
    global_frame: map
    update_frequency: 5.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
